### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tommygebru** [allan-glasier/Colmar-Academy#12]
Hey Allan, don't worry too much about the score, as it's clear you have an excellent understanding of HTML and CSS basics. Spend a little more time reviewing/practicing upon the feedback until it clicks, and I'm confident you'll do fine.

Also keep some HTML/CSS best practices in mind when coding
https://www.codecademy.com/articles
and https://github.com/thenerdery/html-css-standards
When in doubt Google it (or MDN it) 🎉

Ok Allan keep up the good work and happy coding!

**Comment by allan-glasier** [comment]
Thank you so much @tommygebru for taking the time to go through my project and your very detailed comments! I will take everything in consideration on all projects I work one. I appreciate the feedback and helpful tips!
